"""Execution guardrails for the HEP analysis agent."""

from __future__ import annotations

import os
import subprocess
import sys
from dataclasses import dataclass
from enum import Enum
from typing import Sequence


class JobTier(str, Enum):
    LOCAL = "local"
    MODERATE = "moderate"
    EXPENSIVE = "expensive"


@dataclass
class GuardrailDecision:
    allowed: bool
    tier: JobTier
    reason: str


# Thresholds for job classification
MAX_EVENTS_LOCAL = 10_000
MAX_EVENTS_MODERATE = 500_000


def classify_job(*, max_events: int | None, use_xrootd: bool, submit_reana: bool) -> JobTier:
    if submit_reana:
        return JobTier.EXPENSIVE
    if use_xrootd and (max_events is None or max_events > MAX_EVENTS_MODERATE):
        return JobTier.EXPENSIVE
    if use_xrootd or (max_events and max_events > MAX_EVENTS_LOCAL):
        return JobTier.MODERATE
    return JobTier.LOCAL


def check_execution(
    *,
    max_events: int | None,
    use_xrootd: bool,
    submit_reana: bool,
    approve_expensive: bool = False,
) -> GuardrailDecision:
    tier = classify_job(
        max_events=max_events,
        use_xrootd=use_xrootd,
        submit_reana=submit_reana,
    )
    if tier == JobTier.EXPENSIVE and not approve_expensive:
        return GuardrailDecision(
            allowed=False,
            tier=tier,
            reason=(
                "Expensive job blocked: REANA submission or large XRootD read requires "
                "--approve-expensive or interactive approval."
            ),
        )
    return GuardrailDecision(allowed=True, tier=tier, reason=f"Job tier: {tier.value}")


def sandbox_run(
    cmd: Sequence[str],
    *,
    cwd: str | None = None,
    env: dict[str, str] | None = None,
    timeout_sec: int = 3600,
) -> subprocess.CompletedProcess[str]:
    """Run a command in a restricted subprocess (no shell=True)."""
    merged_env = {**os.environ, **(env or {})}
    # Prevent accidental credential leakage into child processes
    for key in ("AWS_SECRET_ACCESS_KEY", "REANA_ACCESS_TOKEN"):
        if key in merged_env and not env:
            pass  # allow if explicitly passed

    return subprocess.run(
        list(cmd),
        cwd=cwd,
        env=merged_env,
        capture_output=True,
        text=True,
        timeout=timeout_sec,
        check=False,
    )


def require_human_disclaimer() -> str:
    return (
        "DISCLAIMER: This report was generated by an automated analysis agent. "
        "A qualified physicist must review all selections, systematics, and "
        "statistical interpretations before any scientific claim is made."
    )
