"""Generate reproducibility report from analysis + validation outputs."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from agent.guardrails import require_human_disclaimer
from agent.validation_agent import ValidationResult


def render_report(
    *,
    request: str,
    run_id: str,
    summary: dict[str, Any],
    validation: ValidationResult,
    trace_path: Path | None,
    dataset_key: str,
    container_image: str,
) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    cf = summary.get("cutflow", {})
    fit = summary.get("fit", {})
    steps = cf.get("steps", [])

    cutflow_table = "\n".join(
        f"| {s['name']} | {s['passing']:,} |" for s in steps
    ) or "| (none) | 0 |"

    val_checks = "\n".join(
        f"- **{c['name']}**: {'PASS' if c['passed'] else 'FAIL'}"
        for c in validation.checks
    )

    return f"""# Reproducibility Report

**Run ID:** `{run_id}`  
**Generated:** {ts}  
**Request:** {request}

---

## Disclaimer

{require_human_disclaimer()}

---

## Configuration

| Item | Value |
|------|-------|
| Dataset | `{dataset_key}` |
| Container | `{container_image}` |
| Source | `{summary.get('source', 'unknown')}` |
| Dry run | `{summary.get('dry_run', False)}` |
| Max events | `{summary.get('max_events', 'all')}` |

---

## Cut-flow

| Step | Passing events |
|------|----------------|
{cutflow_table}

**Initial:** {cf.get('initial', 0):,} → **Final:** {cf.get('final', 0):,}

---

## Statistical fit (J/ψ)

```json
{json.dumps(fit, indent=2)}
```

---

## Validation agent

**Overall:** {'PASSED' if validation.passed else 'FAILED'}

{val_checks}

### Errors
{chr(10).join(f'- {e}' for e in validation.errors) or '- (none)'}

### Warnings
{chr(10).join(f'- {w}' for w in validation.warnings) or '- (none)'}

---

## Artifacts

```json
{json.dumps(summary.get('artifacts', {}), indent=2)}
```

---

## Tool trace

Trace file: `{trace_path or 'N/A'}`

---

## Evidence graph (claim → source)

| Claim | Code | Data | Config | Artifact |
|-------|------|------|--------|----------|
| Dimuon mass spectrum reproduced | `analysis/dimuon_processor.py` | `{dataset_key}` | `config/datasets.yaml` | `dimuon_spectrum.png` |
| Cut-flow documented | `analysis/cutflow.py` | same | `config/invariants.yaml` | `cutflow.json` |
| J/ψ mass extracted | `analysis/dimuon_processor.py::fit_jpsi_peak` | selected dimuons | — | `fit_results.json` |
| Validation passed | `agent/validation_agent.py` | outputs/ | `config/invariants.yaml` | this report |

---

*Report generated by hep-repro-agent v0.1.0*
"""


def write_report(path: Path, content: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return path
